//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerArticle.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messenger
    {
        public int C__Мессенджера { get; set; }
        public System.DateTime Время { get; set; }
        public string Логин_пользователя { get; set; }
        public string Сообщение { get; set; }
    }
}
