//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerArticle.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Feedback = new HashSet<Feedback>();
        }
    
        public int C__Заказа { get; set; }
        public string Заказчик { get; set; }
        public string Тема { get; set; }
        public string Название { get; set; }
        public string Подробное_описание { get; set; }
        public int Количество_символов { get; set; }
        public decimal Бюджет { get; set; }
        public string Назначенный_фрилансер { get; set; }
        public string Состояние { get; set; }
        public string Файл { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual Freelancer Freelancer { get; set; }
    }
}
